# Generated by Django 5.1.1 on 2024-10-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acara',
            name='idKategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acara', to='catering1.categori', verbose_name='idCategori'),
        ),
    ]
