# Generated by Django 5.1.1 on 2024-10-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0002_alter_acara_idkategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriMenu',
            fields=[
                ('idKategori', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Kategori')),
                ('namaKategori', models.CharField(max_length=100, verbose_name='Nama Kategori')),
            ],
            options={
                'verbose_name': 'Kategori Menu',
                'verbose_name_plural': 'Kategori Menu',
            },
        ),
        migrations.AlterField(
            model_name='cateringmenu',
            name='idKategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='catering1.categori', verbose_name='ID Kategori'),
        ),
    ]
