# Generated by Django 5.1.1 on 2024-10-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0004_rename_idkategori_categorimenu_idkate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorimenu',
            name='idKate',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='idKate'),
        ),
        migrations.AlterField(
            model_name='cateringmenu',
            name='idKate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='catering1.categori', verbose_name='idKate'),
        ),
    ]
