# Generated by Django 5.1.1 on 2024-10-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0010_alter_pemesananacara_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idPemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailpem', to='catering1.pemesananpelanggan', verbose_name='ID Pemesanan'),
        ),
    ]
