# Generated by Django 5.1.1 on 2024-10-29 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0012_alter_detailpemesanan_jumlahitemmenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesananacara',
            name='idPelanggan',
        ),
        migrations.AddField(
            model_name='pemesananacara',
            name='idAcara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catering1.acara', verbose_name='ID Acara'),
        ),
    ]
