# Generated by Django 5.1.1 on 2024-11-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0013_remove_pemesananacara_idpelanggan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringmenu',
            options={'verbose_name': 'Catering Menu', 'verbose_name_plural': 'Catering Menu'},
        ),
    ]
