# Generated by Django 5.1.1 on 2024-11-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0014_alter_cateringmenu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acara',
            options={'verbose_name_plural': 'Acara'},
        ),
        migrations.AlterModelOptions(
            name='categori',
            options={'verbose_name_plural': 'Kategori Acara'},
        ),
        migrations.AlterModelOptions(
            name='categorimenu',
            options={'verbose_name_plural': 'Kategori Menu'},
        ),
        migrations.AlterModelOptions(
            name='detailpemesanan',
            options={'verbose_name_plural': 'Detail Pemesanan Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='detailpemesananacara',
            options={'verbose_name_plural': 'Detail Pemesanan Acara'},
        ),
        migrations.AlterModelOptions(
            name='notelepon',
            options={'verbose_name_plural': 'Nomor Telepon'},
        ),
        migrations.AlterModelOptions(
            name='pemesananacara',
            options={'verbose_name_plural': 'Pemesanan Acara'},
        ),
        migrations.AlterModelOptions(
            name='pemesananpelanggan',
            options={'verbose_name_plural': 'Pemesanan Pelanggan'},
        ),
    ]
