# Generated by Django 5.1.1 on 2024-11-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0015_alter_acara_options_alter_categori_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailpemesanan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detailpemesananacara',
            options={},
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering1.cateringmenu', verbose_name='Menu Catering'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idPemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailpem', to='catering1.pemesananpelanggan'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='jumlahItemMenu',
            field=models.PositiveIntegerField(verbose_name='Jumlah Item'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detail Pemesanan Acara'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='idMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering1.cateringmenu', verbose_name='Menu Catering'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='idPemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailAcara', to='catering1.pemesananacara'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='jumlahItemMenu',
            field=models.PositiveIntegerField(verbose_name='Jumlah Item'),
        ),
    ]
