# Generated by Django 5.1.1 on 2024-11-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0016_alter_detailpemesanan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acara',
            options={'verbose_name': 'Acara', 'verbose_name_plural': 'Acara'},
        ),
        migrations.AlterModelOptions(
            name='categori',
            options={'verbose_name': 'Kategori Acara', 'verbose_name_plural': 'Kategori Acara'},
        ),
        migrations.AlterModelOptions(
            name='categorimenu',
            options={'verbose_name': 'Kategori Menu', 'verbose_name_plural': 'Kategori Menu'},
        ),
        migrations.AlterModelOptions(
            name='detailpemesanan',
            options={'verbose_name': 'Detail Pemesanan Pelanggan', 'verbose_name_plural': 'Detail Pemesanan Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='detailpemesananacara',
            options={'verbose_name': 'Detail Pemesanan Acara', 'verbose_name_plural': 'Detail Pemesanan Acara'},
        ),
        migrations.AlterModelOptions(
            name='notelepon',
            options={'verbose_name': 'Nomor Telepon', 'verbose_name_plural': 'Nomor Telepon'},
        ),
        migrations.AlterModelOptions(
            name='pemesananacara',
            options={'verbose_name': 'Pemesanan Acara', 'verbose_name_plural': 'Pemesanan Acara'},
        ),
        migrations.AlterModelOptions(
            name='pemesananpelanggan',
            options={'verbose_name': 'Pemesanan Pelanggan', 'verbose_name_plural': 'Pemesanan Pelanggan'},
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering1.cateringmenu', verbose_name='ID Menu'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idPemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailpem', to='catering1.pemesananpelanggan', verbose_name='ID Pemesanan'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='jumlahItemMenu',
            field=models.PositiveIntegerField(verbose_name='Jumlah Item Menu'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detail Pemesanan'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='idMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering1.cateringmenu', verbose_name='ID Menu'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='idPemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailAcara', to='catering1.pemesananacara', verbose_name='ID Pemesanan'),
        ),
        migrations.AlterField(
            model_name='detailpemesananacara',
            name='jumlahItemMenu',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Item Menu'),
        ),
    ]
