# Generated by Django 5.1.1 on 2024-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0017_alter_acara_options_alter_categori_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'verbose_name': 'Pelanggan', 'verbose_name_plural': 'Pelanggan'},
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('non-aktif', 'Non-Aktif')], default='aktif', max_length=20, verbose_name='Status'),
        ),
    ]
