# Generated by Django 5.1.1 on 2024-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0018_alter_pelanggan_options_pelanggan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringmenu',
            name='stok',
        ),
        migrations.AddField(
            model_name='cateringmenu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/myapp/img/'),
        ),
    ]
