# Generated by Django 5.1.1 on 2024-11-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0020_alter_cateringmenu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesananpelanggan',
            name='status',
            field=models.CharField(choices=[('tertunda', 'Tertunda'), ('konfirmasi', 'Dikonfirmasi'), ('dibatalkan', 'Dibatalkan'), ('dikirim', 'Dikirim'), ('diterima', 'Diterima')], default='tertunda', max_length=20, verbose_name='Status Pesanan'),
        ),
    ]
