# Generated by Django 5.1.1 on 2024-11-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering1', '0022_pelanggan_password_pelanggan_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
